apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-assignment-platform-user-integration
spec:
  selector:
    matchLabels:
      app: vap-users
  replicas: 1
  template:
    metadata:
      labels:
        app: vap-users
    spec:
      containers:
      - name: vap-users
        image: narminsh/vapusers1:amd84
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      
      
        
---
apiVersion: v1
kind: Service
metadata:
  name: vap-users-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    app: vap-users
