apiVersion: apps/v1
kind: Deployment
metadata:
  name: vap-candidates
  labels:
    app: vap-candidates
spec:
  selector:
    matchLabels:
      lbtype: external
  replicas: 1
  template:
    metadata:
      labels:
        lbtype: external
        app: vap-candidates
    spec:
      imagePullSecrets: 
        - name: registry-credentials
      containers:
      - name: vap-candidates
        image: registry.gitlab.com/kibrit/p7362/volunteer-assignment-platform/volunteer-assignment-platform-user-integration
        resources:
          limits:
            memory: "1024Mi"
            cpu: "900m"
        env:
        - name: POSTGRES_USER
          value: "vapadmin"
        - name: POSTGRES_PASSWORD
          value: "DB.4.Vols"
        - name:  POSTGRES_DB
          value: "vap"
        - name:  POSTGRES_HOST
          value: "vap-db.postgres.database.azure.com"
        - name:  POSTGRES_PORT
          value: "5432"
       

---
apiVersion: v1
kind: Service
metadata:
  name: vap-candidates  
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: vap-candidates