version: '3.7'

services:
  postgres:
    image: postgres:9.6.6
    restart: always
    volumes:
        - ./pgdb/:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080