version: '3.7'

services:
  vap-db:
    image: postgres:9.6.6
    restart: always
    ports:
        - "5432:5432"
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # web:
  #   build: .
  #   command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - vap-db
